name: Build Binaries And Release

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:

  createRelease:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Release
        uses: softprops/action-gh-release@v1

  releases-matrix:
    name: Release Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64, 386, loong64]
        exclude:
          - goarch: arm64
            goos: windows
          - goarch: 386
            goos: darwin
          - goarch: 386
            goos: windows
          - goarch: loong64
            goos: windows
          - goarch: loong64
            goos: darwin
    steps:
      - name: Create VERSION file
        run: echo $(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) > VERSION
      - name: Build And Release
        uses: wangyoucao577/go-release-action@v1.39
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./cli"
#          goversion: 1.21
          pre_command: go work init cli analyzer util
          binary_name: opensca-cli
          extra_files: README.md config.json db-demo.json VERSION